package com.mycompany.ksiazkakucharska;

import java.awt.Component;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 * @author mikolaj
 */
public class NewJFrame extends javax.swing.JFrame {

    private Repository repository;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wybierz_kategorie = new javax.swing.JDialog();
        mainPage = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        byDescriptionSearch = new javax.swing.JRadioButton();
        appTitle = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        categoriesButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        byCategoriesSearch = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        Wyszukiwanie1_4 = new javax.swing.JPanel();
        ile_wynikow = new java.awt.Label();
        P1Z = new javax.swing.JLabel();
        P1T = new javax.swing.JLabel();
        P2Z = new javax.swing.JLabel();
        P2T = new javax.swing.JLabel();
        P4Z = new javax.swing.JLabel();
        P3Z = new javax.swing.JLabel();
        P4T = new javax.swing.JLabel();
        P3T = new javax.swing.JLabel();
        wroc2 = new javax.swing.JButton();
        categoriesPage = new javax.swing.JPanel();
        appTitle2 = new javax.swing.JLabel();
        pom1 = new javax.swing.JLabel();
        lista_przepisow = new java.awt.List();
        pom = new javax.swing.JLabel();
        recipePage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wyswietl_tekst = new javax.swing.JLabel();
        wyswietl_zdjecie = new javax.swing.JLabel();
        zapisz = new javax.swing.JButton();
        drukuj = new javax.swing.JButton();
        wroc = new javax.swing.JButton();
        tytul_przepisu = new javax.swing.JLabel();
        aboutPage = new javax.swing.JPanel();
        wroc5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        wybierz_kategorie.setTitle("Błąd");
        wybierz_kategorie.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout wybierz_kategorieLayout = new javax.swing.GroupLayout(wybierz_kategorie.getContentPane());
        wybierz_kategorie.getContentPane().setLayout(wybierz_kategorieLayout);
        wybierz_kategorieLayout.setHorizontalGroup(
            wybierz_kategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        wybierz_kategorieLayout.setVerticalGroup(
            wybierz_kategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1000, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPage.setBackground(new java.awt.Color(255, 245, 186));
        mainPage.setAlignmentX(0.0F);
        mainPage.setAlignmentY(0.0F);
        mainPage.setPreferredSize(new java.awt.Dimension(1000, 600));
        mainPage.setLayout(null);

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        mainPage.add(searchInput);
        searchInput.setBounds(340, 30, 350, 50);

        byDescriptionSearch.setBackground(new java.awt.Color(255, 245, 186));
        byDescriptionSearch.setText("Wg. Treści");
        byDescriptionSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byDescriptionSearchActionPerformed(evt);
            }
        });
        mainPage.add(byDescriptionSearch);
        byDescriptionSearch.setBounds(340, 90, 110, 23);

        appTitle.setText("app icon");
        mainPage.add(appTitle);
        appTitle.setBounds(10, 10, 232, 155);

        menuButton.setText("☰");
        menuButton.setName("menuButton"); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        mainPage.add(menuButton);
        menuButton.setBounds(860, 40, 60, 30);

        settingsButton.setText("+");
        settingsButton.setName("settingsButton"); // NOI18N
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        mainPage.add(settingsButton);
        settingsButton.setBounds(790, 40, 60, 30);

        aboutButton.setText("O aplikacji");
        aboutButton.setName("aboutButton"); // NOI18N
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        mainPage.add(aboutButton);
        aboutButton.setBounds(800, 110, 180, 23);

        categoriesButton.setText("Kategorie przepisów");
        categoriesButton.setName("categoriesButton"); // NOI18N
        categoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesButtonActionPerformed(evt);
            }
        });
        mainPage.add(categoriesButton);
        categoriesButton.setBounds(800, 80, 180, 23);

        image.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        image.setText("testst");
        mainPage.add(image);
        image.setBounds(0, 150, 1000, 450);

        byCategoriesSearch.setBackground(new java.awt.Color(255, 245, 186));
        byCategoriesSearch.setText("Wg. Kategorii");
        byCategoriesSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byCategoriesSearchActionPerformed(evt);
            }
        });
        mainPage.add(byCategoriesSearch);
        byCategoriesSearch.setBounds(470, 90, 150, 23);

        searchButton.setText("SZUKAJ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        mainPage.add(searchButton);
        searchButton.setBounds(700, 40, 80, 30);

        Wyszukiwanie1_4.setBackground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie1_4.setForeground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie1_4.setAlignmentX(0.0F);
        Wyszukiwanie1_4.setAlignmentY(0.0F);
        Wyszukiwanie1_4.setPreferredSize(new java.awt.Dimension(1000, 600));
        Wyszukiwanie1_4.setLayout(null);

        ile_wynikow.setText("ZNALEZIONO WYNIKÓW");
        Wyszukiwanie1_4.add(ile_wynikow);
        ile_wynikow.setBounds(30, 10, 190, 80);

        P1Z.setBackground(new java.awt.Color(240, 240, 40));
        P1Z.setText("P1Z");
        P1Z.setName("P1Z"); // NOI18N
        P1Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P1Z);
        P1Z.setBounds(80, 100, 200, 200);

        P1T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P1T.setText("P1T");
        P1T.setName("P1T"); // NOI18N
        P1T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P1T);
        P1T.setBounds(80, 330, 190, 40);

        P2Z.setText("P2Z");
        P2Z.setName("P1Z"); // NOI18N
        P2Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P2Z);
        P2Z.setBounds(320, 100, 200, 200);

        P2T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P2T.setText("P2T");
        P2T.setName("P1T"); // NOI18N
        P2T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P2T);
        P2T.setBounds(320, 330, 160, 50);

        P4Z.setText("P4Z");
        P4Z.setName("P1Z"); // NOI18N
        P4Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P4TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P4Z);
        P4Z.setBounds(750, 100, 200, 200);

        P3Z.setText("P3Z");
        P3Z.setName("P1Z"); // NOI18N
        P3Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P3TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P3Z);
        P3Z.setBounds(530, 100, 200, 200);

        P4T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P4T.setText("P4T");
        P4T.setName("P1T"); // NOI18N
        P4T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P4TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P4T);
        P4T.setBounds(750, 340, 200, 40);

        P3T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P3T.setText("P3T");
        P3T.setName("P1T"); // NOI18N
        P3T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P3TMouseClicked(evt);
            }
        });
        Wyszukiwanie1_4.add(P3T);
        P3T.setBounds(530, 340, 140, 40);

        wroc2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wroc2.setText("Wróć do menu głównego");
        wroc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });
        Wyszukiwanie1_4.add(wroc2);
        wroc2.setBounds(350, 510, 220, 30);

        categoriesPage.setBackground(new java.awt.Color(255, 245, 186));
        categoriesPage.setForeground(new java.awt.Color(255, 245, 186));
        categoriesPage.setAlignmentX(0.0F);
        categoriesPage.setAlignmentY(0.0F);
        categoriesPage.setPreferredSize(new java.awt.Dimension(1000, 600));
        categoriesPage.setLayout(null);

        appTitle2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appTitle2.setText("appTitle2");
        categoriesPage.add(appTitle2);
        appTitle2.setBounds(350, 20, 232, 155);
        categoriesPage.add(pom1);
        pom1.setBounds(698, 90, 90, 50);

        lista_przepisow.setBackground(new java.awt.Color(102, 102, 255));
        lista_przepisow.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lista_przepisow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_przepisowActionPerformed(evt);
            }
        });
        lista_przepisow.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lista_przepisowPropertyChange(evt);
            }
        });
        categoriesPage.add(lista_przepisow);
        lista_przepisow.setBounds(280, 230, 370, 340);

        pom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pom.setText("Wybierz kategorie aby zobaczyć znajdujące się w niej przepisy");
        pom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pomMouseClicked(evt);
            }
        });
        categoriesPage.add(pom);
        pom.setBounds(220, 170, 500, 50);

        recipePage.setBackground(new java.awt.Color(255, 245, 186));
        recipePage.setForeground(new java.awt.Color(255, 245, 186));
        recipePage.setAlignmentX(0.0F);
        recipePage.setAlignmentY(0.0F);
        recipePage.setPreferredSize(new java.awt.Dimension(1000, 600));
        recipePage.setLayout(null);

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane3.setAutoscrolls(true);

        wyswietl_tekst.setBackground(new java.awt.Color(102, 102, 255));
        wyswietl_tekst.setText("tu wyświetl tekst");
        wyswietl_tekst.setToolTipText("");
        jScrollPane3.setViewportView(wyswietl_tekst);

        recipePage.add(jScrollPane3);
        jScrollPane3.setBounds(10, 80, 660, 502);
        recipePage.add(wyswietl_zdjecie);
        wyswietl_zdjecie.setBounds(690, 80, 256, 256);

        zapisz.setText("ZAPISZ PRZEPIS");
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });
        recipePage.add(zapisz);
        zapisz.setBounds(690, 350, 250, 23);

        drukuj.setText("DRUKUJ PRZEPIS");
        drukuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drukujActionPerformed(evt);
            }
        });
        recipePage.add(drukuj);
        drukuj.setBounds(690, 380, 250, 23);

        wroc.setText("WRÓĆ DO MENU GŁÓWNEGO");
        wroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocActionPerformed(evt);
            }
        });
        recipePage.add(wroc);
        wroc.setBounds(700, 530, 240, 23);

        tytul_przepisu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tytul_przepisu.setText("tytul przepisu");
        recipePage.add(tytul_przepisu);
        tytul_przepisu.setBounds(10, 20, 240, 40);

        aboutPage.setBackground(new java.awt.Color(255, 245, 186));
        aboutPage.setForeground(new java.awt.Color(255, 245, 186));
        aboutPage.setAlignmentX(0.0F);
        aboutPage.setAlignmentY(0.0F);
        aboutPage.setPreferredSize(new java.awt.Dimension(1000, 600));

        wroc5.setText("Wróć do menu głównego");
        wroc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("<html>Ta aplikacja powstała jako projekt zaliczeniowy z przedmiotu Programowanie w Javie. <br>Jest ona wirtualną książką kucharską z funkcją wyszukiwania przepisów, <br> jak również zapisywania oraz drukowania ich zawartości. <br>Autorzy:<br>* Julia Olszewska <br> * Andrzej Koziński <br> * Mikołaj Sobiegraj</html>");

        javax.swing.GroupLayout aboutPageLayout = new javax.swing.GroupLayout(aboutPage);
        aboutPage.setLayout(aboutPageLayout);
        aboutPageLayout.setHorizontalGroup(
            aboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wroc5)
                .addGap(53, 53, 53))
        );
        aboutPageLayout.setVerticalGroup(
            aboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPageLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(wroc5)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(categoriesPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Wyszukiwanie1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(recipePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(categoriesPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Wyszukiwanie1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(recipePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //VIEW        
    void wyswietlprzepis(JLabel label) {
        if (Wyszukiwanie1_4.isVisible()) {
            Wyszukiwanie1_4.setVisible(false);
        }

        recipePage.setVisible(true); // TODO add your handling code here:

        String tytul = label.getText();
        Recipe wybranyprzepis = null;
        for (Recipe przepisy1 : repository.getAllRecipies()) {
            if (przepisy1.getTitle() == null ? tytul == null : przepisy1.getTitle().equals(tytul)) {
                wybranyprzepis = przepisy1;
            }
        }
        View view = new View();
        Controller controller = new Controller(wybranyprzepis, view);
        controller.wyswietl_caly_przepis_controller(wyswietl_zdjecie, wyswietl_tekst, wybranyprzepis.getTekstPrzepisuSformatowany());
        tytul_przepisu.setText(wybranyprzepis.getTitle());

    }

    public JLabel znajdz_label(String nazwa) {

        for (int j = 0; j <= Wyszukiwanie1_4.getComponents().length; j++) {
            if (Wyszukiwanie1_4.getComponent(j) instanceof JLabel) {
                JLabel label = (JLabel) Wyszukiwanie1_4.getComponent(j);
                if (label.getText() == null ? nazwa == null : label.getText().equals(nazwa)) {
                    return label;
                }

            }
        }
        return null;
    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mainPage.setVisible(true);
        Wyszukiwanie1_4.setVisible(false);
        recipePage.setVisible(false);
        aboutPage.setVisible(false);
        categoriesPage.setVisible(false);
        categoriesButton.setVisible(false);
        aboutButton.setVisible(false);

        initializeRepository();

        String grafika = System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\cookbook4.png";
        ImageIcon imageIcon = new ImageIcon(grafika);
        image.setText("");
        image.setIcon(imageIcon);
        String grafika2 = System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\CBbannerFV.png";
        ImageIcon imageIcon2 = new ImageIcon(grafika2);
        appTitle.setText("");
        appTitle.setIcon(imageIcon2);
        String grafika3 = System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\CBbannerFV.png";
        ImageIcon imageIcon3 = new ImageIcon(grafika3);
        appTitle2.setText("");
        appTitle2.setIcon(imageIcon3);

    }//GEN-LAST:event_formWindowOpened

    private void initializeRepository() {
        repository = new Repository();
        Recipe recipe = new Recipe();
        recipe.addCategory("Desery");
        recipe.addCategory("Kuchnia Polska");
        recipe.addCategory("Wegetariańskie");
        recipe.setTitle("Szarlotka");
        recipe.addIngredients("300 g mąki\n"
                + "    250 g zimnego masła (50 g masła można zastąpić smalcem)\n"
                + "    1,5 łyżeczki proszku do pieczenia\n"
                + "    5 łyżek cukru\n"
                + "    1 łyżka cukru wanilinowego\n"
                + "    1 jajko"
                + "     1,5 kg jabłek na szarlotkę (szara reneta, antonówka) lub 1 słoik ok. 800 g gotowych jabłek\n"
                + "    5 łyżek cukru\n"
                + "    1/2 łyżeczki cynamonu\n"
                + "    cukier puder");
        recipe.setDescription("\\nCIASTO\\n\"\n"
                + "\\n\"\n"
                + "    Z podanych składników zagnieść ciasto kruche (w robocie kuchennym lub na stolnicy): do przesianej mąki dodać pokrojone w kostkę zimne masło, proszek do pieczenia, cukier i cukier wanilinowy.\\n\"\n"
                + "    Rozdrabniać składniki na kruszonkę, pod koniec dodać jajko i połączyć składniki w jednolite i gładkie ciasto (może być klejące).\\n\"\n"
                + "    Włożyć do zamrażarki na ok. 15 - 30 minut.\\n\"\n"
                + "\\n\"\n"
                + "JABŁKA\\n\"\n"
                + "\\n\"\n"
                + "    Jabłka obrać, pokroić na ćwiartki i wyciąć gniazda nasienne. Pokroić na mniejsze kawałki i włożyć do szerokiego garnka lub głęboką patelnię.\\n\"\n"
                + "    Dodać cukier i smażyć przez ok. 10 - 15 minut co chwilę mieszając, aż jabłka zmiękną i zaczną się rozpadać. Pod koniec dodać cynamon.\\n\"\n"
                + "\\n\"\n"
                + "PIECZENIE\\n\"\n"
                + "\\n\"\n"
                + "    Piekarnik nagrzać do 180 stopni C. Przygotować małą foremkę (np. o średnicy 26 cm lub 21 x 28 cm lub 24 x 24 cm).\\n\"\n"
                + "    Wyjąć jedną połówkę ciasta z zamrażarki, pokroić nożem na plasterki i wylepić nimi spód formy, doklejając brakujące miejsca palcami.\\n\"\n"
                + "    Na spód wyłożyć jabłka.\\n\"\n"
                + "    Pozostałe ciasto zetrzeć na tarce bezpośrednio na jabłka (lub pokroić ciasto na plasterki i ułożyć na wierzchu).\\n\"\n"
                + "    Wstawić do piekarnika i piec przez ok. 50 - 55 minut na złoty kolor. Posypać cukrem pudrem. Pokroić po ostudzeniu.\\n\"");
        recipe.setImagePath(System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\szarlotka.jpg");

        Recipe recipe2 = new Recipe();
        recipe2.addCategory("Mięsne");
        recipe2.addCategory("Kuchnia Polska");
        recipe2.setTitle("Kurczak w sosie");
                recipe2.addIngredients("2 pojedyncze filety kurczaka\n" +
"1/2 łyżeczki kurkumy, 1 łyżeczka słodkiej papryki, szczypta ostrej\n" +
"150 g pieczarek\n" +
"1 mała cebula\n" +
"2/3 szklanki bulionu drobiowego\n" +
"1 łyżka posiekanego koperku\n" +
"1/2 szklanki śmietanki 30% lub 18% (do zup i sosów)\n" +
"po 1 łyżce oleju, masła i mąki pszennej");
        recipe2.setImagePath(System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\kurczak.jpg");
        recipe2.setDescription("•	Kurczaka oczyścić z błonek i kostek, pokroić na mniejsze filety w następujący sposób: odkroić polędwiczkę, następnie filet przekroić pionowo na dwie połówki. Grubszą połówkę przekroić jeszcze wzdłuż na 2 cieńsze części.\n" +
"•	Mięso rozbić tłuczkiem na jednakową grubość, ok. 1 cm. Doprawić solą, pieprzem, kurkumą oraz paprykami. Wymieszać z łyżką oleju i obtoczyć w mące.\n" +
"•	Pieczarki umyć i dokładnie osuszyć, następnie pokroić na cienkie plasterki. Cebulę pokroić w kosteczkę. \n" +
"•	Rozgrzać patelnię z olejem, włożyć filety kurczaka, smażyć po ok. 2 minuty z każdej strony na większym ogniu. Wyjąć na talerz.\n" +
"•	Na tę samą patelnię włożyć cebulę i delikatnie ją podsmażyć, następnie dodać pieczarki oraz masło i smażyć co chwilę mieszając przez ok. 3 - 4 minuty, aż pieczarki lekko się zrumienią.\n" +
"•	Włożyć z powrotem mięso na patelnię i wsunąć je pomiędzy pieczarki. Trzymając danie na ogniu wlać bulion i zagotować.\n" +
"•	Dodać koperek oraz śmietankę, delikatnie przemieszać składniki potrząsając patelnią. Gotować przez ok. 1 - 2  minuty aż sos zgęstnieje.");
        
                Recipe recipe3 = new Recipe();
        recipe3.addCategory("Rybne");
        recipe3.setTitle("Łosoś ze szparagami");
                recipe3.addIngredients("1 pęczek szparagów\n" +
"ok. 600 g filetów łososia\n" +
"2 ząbki czosnku\n" +
"1 łyżka mąki pszennej\n" +
"1 łyżka oliwy\n" +
"1/2 cebuli\n" +
"2/3 szklanki bulionu\n" +
"125 ml śmietanki 30%\n" +
"2 łyżeczki posiekanego koperku");
        recipe3.setImagePath(System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\losos.jpg");
        recipe3.setDescription("•	Szparagi umyć i odłamać grube końce (same złamią się w odpowiednim miejscu). Końce nie będą wykorzystane. Łodyżki pokroić ukośnie na ok. 1/2 cm plasterki, główki pozostawić w całości.\n" +
"•	Odciąć skórę z łososia, pokroić go na porcje, doprawić solą, pieprzem, natrzeć przeciśniętym przez praskę czosnkiem i obtoczyć w mące.\n" +
"•	Rozgrzać patelnię z oliwą, włożyć łososia i na nieco większym ogniu obsmażyć go z dwóch stron, po około 1 minucie (w środku ma pozostać surowy). Delikatnie odłożyć na talerz.\n" +
"•	Na tę samą patelnię włożyć pokrojoną w kosteczkę cebulę. Smażyć przez ok. 3 minuty często mieszając.\n" +
"•	Dodać pokrojone szparagi (łodyżki i główki) i mieszając smażyć przez ok. 1 - 2 minuty. Wlać bulion i po zagotowaniu gotować jeszcze przez ok. 3 minuty. Doprawić świeżo zmielonym pieprzem.\n" +
"•	Wlać śmietankę i wymieszać. W powstały sos włożyć podsmażonego łososia, posypać koperkiem i gotować przez ok. 2 minuty. Sos można doprawić solą w razie potrzeby.");
        
                        Recipe recipe4 = new Recipe();
        recipe4.addCategory("Mięsne");
        recipe4.setTitle("Tortilla wołowa");
                recipe4.addIngredients("4 tortille\n" +
"1 cebula\n" +
"400 g mielonego mięsa wołowego\n" +
"1 łyżka przyprawy kuchni meksykańskiej*\n" +
"2 łyżeczki koncentratu pomidorowego\n" +
"1 mała puszka czerwonej fasoli\n" +
"1 mała puszka kukurydzy\n" +
"5 kawałków suszonych pomidorów (opcjonalnie)\n" +
"1 puszka krojonych pomidorów\n" +
"300 g tartego żółtego sera (np. żółta mozzarella plus cheddar)\n" +
"świeża kolendra\n" +
"olej roślinny");
        recipe4.setImagePath(System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\tortilla.jpg");
        recipe4.setDescription("•	Na dużej patelni na 2 łyżkach oleju zeszklić pokrojoną w kosteczkę cebulę (ok. 7 minut). Dodać zmielone mięso, posypać przyprawami i mieszając obsmażyć aż zmieni kolor. Przykryć i smażyć dalej na małym ogniu przez 15 minut.\n" +
"•	Dodać koncentrat pomidorowy, odcedzoną fasolkę i kukurydzę oraz (opcjonalnie) pokrojone suszone pomidory. Wymieszać i gotować wszystko jeszcze przez ok. 5 minut.\n" +
"•	Farsz wyłożyć na tortille, posypać serem (zachować ok. 1/3 ilości sera na wierzch) i zwinąć w rulony, ułożyć w naczyniu żaroodpornym.\n" +
"•	Krojone pomidory doprawić solą, pieprzem, szczyptą cukru i gotować przez ok. 10 minut bez przykrycia. Polać po tortillach i posypać pozostałym serem.\n" +
"•	Piec w piekarniku nagrzanym do 180 stopni C przez ok. 20 minut. Posypać listkami kolendry i podawać.");
        repository.addRecipe(recipe);
        repository.addRecipe(recipe2);
        repository.addRecipe(recipe3);
        repository.addRecipe(recipe4);
    }


    private void P1TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1TMouseClicked
        JLabel label = P1T;
        wyswietlprzepis(label);
    }//GEN-LAST:event_P1TMouseClicked

    private void P2TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2TMouseClicked
        JLabel label = P2T;
        wyswietlprzepis(label);    // TODO add your handling code here:
    }//GEN-LAST:event_P2TMouseClicked

    private void P3TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3TMouseClicked
        JLabel label = P3T;
        wyswietlprzepis(label);       // TODO add your handling code here:
    }//GEN-LAST:event_P3TMouseClicked

    private void P4TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4TMouseClicked
        JLabel label = P4T;
        wyswietlprzepis(label);    // TODO add your handling code here:
    }//GEN-LAST:event_P4TMouseClicked

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed

        try {
            FileWriter myWriter = new FileWriter(tytul_przepisu.getText());
            myWriter.write(wyswietl_tekst.getText());
            myWriter.close();
        } catch (IOException e) {
            System.out.println("Błąd zapisu do pliku");
            e.printStackTrace();
        }
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String tuzapisz = fileChooser.getCurrentDirectory().getAbsolutePath() + "/" + fileChooser.getSelectedFile().getName() + ".txt";

            try {
                Writer output = null;
                File file = new File(tuzapisz);
                output = new BufferedWriter(new FileWriter(file));
                output.write(wyswietl_tekst.getText());
                output.close();

            } catch (Exception e) {
                System.out.println("Błąd w czasie tworzenia pliku");
            }

        }


    }//GEN-LAST:event_zapiszActionPerformed


    private void drukujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drukujActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        if (pj.printDialog()) {
            try {
                pj.print();
            } catch (PrinterException exc) {
                System.out.println(exc);
            }
        }
    }//GEN-LAST:event_drukujActionPerformed

    private void wrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocActionPerformed
        recipePage.setVisible(false);
        mainPage.setVisible(true);
        dispose();//Reset aplikacji
        NewJFrame frame = new NewJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_wrocActionPerformed

    private void wroc2actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wroc2actionPerformed
        Wyszukiwanie1_4.setVisible(false);
        mainPage.setVisible(true);
        dispose();//Reset aplikacji
        NewJFrame frame = new NewJFrame();
        frame.setVisible(true);

    }//GEN-LAST:event_wroc2actionPerformed

    private void categoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesButtonActionPerformed
        mainPage.setVisible(false);
        categoriesPage.setVisible(true);

        for (String kategoria : repository.getAllCategories()) {
            lista_przepisow.add(kategoria);
        }
    }//GEN-LAST:event_categoriesButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        mainPage.setVisible(false);
        aboutPage.setVisible(true);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        if (categoriesButton.isVisible() == false) {
            categoriesButton.setVisible(true);
            aboutButton.setVisible(true);
        } else {
            categoriesButton.setVisible(false);
            aboutButton.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        List<Recipe> wyniki = new ArrayList();
        Wyszukiwanie1_4.setVisible(false);

        if (searchInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(wybierz_kategorie, "Wpisz tekst do wyszukania");
        } else if (!byDescriptionSearch.isSelected() && !byCategoriesSearch.isSelected()) {
            JOptionPane.showMessageDialog(wybierz_kategorie, "Wybierz jedną z kategorii wyszukiwania");
        } else {
            if (byDescriptionSearch.isSelected()) {
                wyniki = repository.getRecipesWithText(searchInput.getText());
                if (wyniki.size() < 1) {
                    JOptionPane.showMessageDialog(wybierz_kategorie, "Brak wyników");
                    dispose();
                    NewJFrame frame = new NewJFrame();
                    frame.setVisible(true);
                }
            }

            if (byCategoriesSearch.isSelected()) {
                wyniki = repository.getRecipesWithCategory(searchInput.getText());
                if (wyniki.size() < 1) {
                    JOptionPane.showMessageDialog(wybierz_kategorie, "Brak wyników");
                    dispose();
                    NewJFrame frame = new NewJFrame();
                    frame.setVisible(true);
                }
            }

            mainPage.setVisible(false);
            Wyszukiwanie1_4.setVisible(true);

            updateSearchResultCount(wyniki.size());

            wroc2.setVisible(true);

            for (int i = 1; i <= wyniki.size(); i++) {
                String nazwa_tekst = "P" + i + "T";
                String nazwa_zdjecie = "P" + i + "Z";
                JLabel label_tekst = znajdz_label(nazwa_tekst);
                label_tekst.setVisible(true);
                JLabel label_zdjecie = znajdz_label(nazwa_zdjecie);
                label_zdjecie.setVisible(true);
                int nowei = i - 1;

                View view = new View();
                Controller controller = new Controller(wyniki.get(nowei), view);
                controller.wyswietl_zdjecie_i_tytul_controller(label_zdjecie, label_tekst);

            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void byCategoriesSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byCategoriesSearchActionPerformed
        if (!byDescriptionSearch.isSelected()) {
            byCategoriesSearch.setSelected(true);
            byDescriptionSearch.setSelected(false);
        } else {
            byCategoriesSearch.setSelected(true);
            byDescriptionSearch.setSelected(false);
        }
        // TODO add your handl  // TODO add your handling code here:
    }//GEN-LAST:event_byCategoriesSearchActionPerformed

    private void byDescriptionSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byDescriptionSearchActionPerformed
        if (!byCategoriesSearch.isSelected()) {
            byDescriptionSearch.setSelected(true);
            byCategoriesSearch.setSelected(false);
        } else {
            byDescriptionSearch.setSelected(true);
            byCategoriesSearch.setSelected(false);

        }// TODO add your handling code here:
    }//GEN-LAST:event_byDescriptionSearchActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void pomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pomMouseClicked

    private void lista_przepisowPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lista_przepisowPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_przepisowPropertyChange

    private void lista_przepisowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_przepisowActionPerformed
        String wybrany = lista_przepisow.getSelectedItem();
        categoriesPage.setVisible(false);
        searchInput.setText(wybrany);
        byCategoriesSearch.setSelected(true);
        searchButtonActionPerformed(evt);
    }//GEN-LAST:event_lista_przepisowActionPerformed

    private void updateSearchResultCount(int count) {
        String a = null;
        if (count == 1) {
            a = "Znaleziono " + count + " wynik";
        }
        if (2 <= count && count <= 4) {
            a = "Znaleziono " + count + " wyniki";
        }
        if (count >= 5) {
            a = "Znaleziono " + count + " wyników";
        }
        ile_wynikow.setText(a);
        ile_wynikow.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NewJFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1T;
    private javax.swing.JLabel P1Z;
    private javax.swing.JLabel P2T;
    private javax.swing.JLabel P2Z;
    private javax.swing.JLabel P3T;
    private javax.swing.JLabel P3Z;
    private javax.swing.JLabel P4T;
    private javax.swing.JLabel P4Z;
    private javax.swing.JPanel Wyszukiwanie1_4;
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel aboutPage;
    private javax.swing.JLabel appTitle;
    private javax.swing.JLabel appTitle2;
    private javax.swing.JRadioButton byCategoriesSearch;
    private javax.swing.JRadioButton byDescriptionSearch;
    private javax.swing.JButton categoriesButton;
    private javax.swing.JPanel categoriesPage;
    private javax.swing.JButton drukuj;
    private java.awt.Label ile_wynikow;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.List lista_przepisow;
    private javax.swing.JPanel mainPage;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel pom;
    private javax.swing.JLabel pom1;
    private javax.swing.JPanel recipePage;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel tytul_przepisu;
    private javax.swing.JButton wroc;
    private javax.swing.JButton wroc2;
    private javax.swing.JButton wroc5;
    private javax.swing.JDialog wybierz_kategorie;
    private javax.swing.JLabel wyswietl_tekst;
    private javax.swing.JLabel wyswietl_zdjecie;
    private javax.swing.JButton zapisz;
    // End of variables declaration//GEN-END:variables
}
