package com.mycompany.ksiazkakucharska;

import java.awt.Component;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 * @author mikolaj
 */
public class NewJFrame extends javax.swing.JFrame {

    private Repository repository;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wybierz_kategorie = new javax.swing.JDialog();
        mainPage = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        byDescriptionSearch = new javax.swing.JRadioButton();
        byCategoriesSearch = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        appTitle = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        categoriesButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        Wyszukiwanie1_4 = new javax.swing.JPanel();
        ile_wynikow = new java.awt.Label();
        P1Z = new javax.swing.JLabel();
        P1T = new javax.swing.JLabel();
        P2Z = new javax.swing.JLabel();
        P2T = new javax.swing.JLabel();
        P4Z = new javax.swing.JLabel();
        P3Z = new javax.swing.JLabel();
        P4T = new javax.swing.JLabel();
        P3T = new javax.swing.JLabel();
        doprzodu1 = new javax.swing.JButton();
        cofnij1 = new javax.swing.JButton();
        wroc2 = new javax.swing.JButton();
        Wyszukiwanie4_8 = new javax.swing.JPanel();
        ile_wynikow1 = new java.awt.Label();
        P5Z = new javax.swing.JLabel();
        P5T = new javax.swing.JLabel();
        P6Z = new javax.swing.JLabel();
        P6T = new javax.swing.JLabel();
        P8Z = new javax.swing.JLabel();
        P7Z = new javax.swing.JLabel();
        P8T = new javax.swing.JLabel();
        P7T = new javax.swing.JLabel();
        doprzodu2 = new javax.swing.JButton();
        cofnij2 = new javax.swing.JButton();
        wroc3 = new javax.swing.JButton();
        Wyszukiwanie8_12 = new javax.swing.JPanel();
        ile_wynikow2 = new java.awt.Label();
        P9Z = new javax.swing.JLabel();
        P9T = new javax.swing.JLabel();
        P10Z = new javax.swing.JLabel();
        P10T = new javax.swing.JLabel();
        P12Z = new javax.swing.JLabel();
        P11Z = new javax.swing.JLabel();
        P12T = new javax.swing.JLabel();
        P11T = new javax.swing.JLabel();
        doprzodu3 = new javax.swing.JButton();
        cofnij3 = new javax.swing.JButton();
        wroc4 = new javax.swing.JButton();
        categoriesPage = new javax.swing.JPanel();
        tytul1 = new javax.swing.JLabel();
        pom1 = new javax.swing.JLabel();
        lista_przepisow = new java.awt.List();
        pom = new javax.swing.JLabel();
        recipePage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wyswietl_tekst = new javax.swing.JLabel();
        wyswietl_zdjecie = new javax.swing.JLabel();
        zapisz = new javax.swing.JButton();
        drukuj = new javax.swing.JButton();
        wroc = new javax.swing.JButton();
        tytul_przepisu = new javax.swing.JLabel();
        aboutPage = new javax.swing.JPanel();
        wroc5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        wybierz_kategorie.setTitle("Błąd");
        wybierz_kategorie.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout wybierz_kategorieLayout = new javax.swing.GroupLayout(wybierz_kategorie.getContentPane());
        wybierz_kategorie.getContentPane().setLayout(wybierz_kategorieLayout);
        wybierz_kategorieLayout.setHorizontalGroup(
            wybierz_kategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        wybierz_kategorieLayout.setVerticalGroup(
            wybierz_kategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1060, 620));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 300));
        setPreferredSize(new java.awt.Dimension(1060, 600));
        setSize(new java.awt.Dimension(1060, 600));
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPage.setBackground(new java.awt.Color(255, 245, 186));
        mainPage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainPage.setAlignmentX(0.0F);
        mainPage.setAlignmentY(0.0F);
        mainPage.setPreferredSize(new java.awt.Dimension(1060, 600));

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        byDescriptionSearch.setBackground(new java.awt.Color(255, 245, 186));
        byDescriptionSearch.setText("Wg. Treści");
        byDescriptionSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byDescriptionSearchActionPerformed(evt);
            }
        });

        byCategoriesSearch.setBackground(new java.awt.Color(255, 245, 186));
        byCategoriesSearch.setText("Wg. Kategorii");
        byCategoriesSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byCategoriesSearchActionPerformed(evt);
            }
        });

        searchButton.setText("SZUKAJ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        appTitle.setText("app icon");

        menuButton.setText("☰");
        menuButton.setName("menuButton"); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        settingsButton.setText("+");
        settingsButton.setName("settingsButton"); // NOI18N
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("O aplikacji");
        aboutButton.setName("aboutButton"); // NOI18N
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        categoriesButton.setText("Kategorie przepisów");
        categoriesButton.setName("categoriesButton"); // NOI18N
        categoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesButtonActionPerformed(evt);
            }
        });

        image.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        image.setText("testst");

        javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
        mainPage.setLayout(mainPageLayout);
        mainPageLayout.setHorizontalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPageLayout.createSequentialGroup()
                                .addComponent(byDescriptionSearch)
                                .addGap(38, 38, 38)
                                .addComponent(byCategoriesSearch))
                            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPageLayout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(settingsButton)
                                .addGap(18, 18, 18)
                                .addComponent(menuButton))
                            .addComponent(categoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1060, 1060, 1060))
            .addGroup(mainPageLayout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPageLayout.setVerticalGroup(
            mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(appTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(categoriesButton))
                    .addGroup(mainPageLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(byCategoriesSearch)
                            .addComponent(byDescriptionSearch))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        Wyszukiwanie1_4.setBackground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie1_4.setForeground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie1_4.setAlignmentX(0.0F);
        Wyszukiwanie1_4.setAlignmentY(0.0F);
        Wyszukiwanie1_4.setPreferredSize(new java.awt.Dimension(1011, 550));

        ile_wynikow.setText("ZNALEZIONO WYNIKÓW");

        P1Z.setText("P1Z");
        P1Z.setName("P1Z"); // NOI18N
        P1Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1TMouseClicked(evt);
            }
        });

        P1T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P1T.setText("P1T");
        P1T.setName("P1T"); // NOI18N
        P1T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1TMouseClicked(evt);
            }
        });

        P2Z.setText("P2Z");
        P2Z.setName("P1Z"); // NOI18N
        P2Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2TMouseClicked(evt);
            }
        });

        P2T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P2T.setText("P2T");
        P2T.setName("P1T"); // NOI18N
        P2T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2TMouseClicked(evt);
            }
        });

        P4Z.setText("P4Z");
        P4Z.setName("P1Z"); // NOI18N
        P4Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P4TMouseClicked(evt);
            }
        });

        P3Z.setText("P3Z");
        P3Z.setName("P1Z"); // NOI18N
        P3Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P3TMouseClicked(evt);
            }
        });

        P4T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P4T.setText("P4T");
        P4T.setName("P1T"); // NOI18N
        P4T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P4TMouseClicked(evt);
            }
        });

        P3T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P3T.setText("P3T");
        P3T.setName("P1T"); // NOI18N
        P3T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P3TMouseClicked(evt);
            }
        });

        doprzodu1.setText("→");
        doprzodu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doprzodu1ActionPerformed(evt);
            }
        });

        cofnij1.setText("←");
        cofnij1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofnij1ActionPerformed(evt);
            }
        });

        wroc2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wroc2.setText("Wróć do menu głównego");
        wroc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Wyszukiwanie1_4Layout = new javax.swing.GroupLayout(Wyszukiwanie1_4);
        Wyszukiwanie1_4.setLayout(Wyszukiwanie1_4Layout);
        Wyszukiwanie1_4Layout.setHorizontalGroup(
            Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wroc2)
                    .addComponent(ile_wynikow, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wyszukiwanie1_4Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                        .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P1Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P1T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P2Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P2T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P3Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P3T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P4Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P4T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wyszukiwanie1_4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cofnij1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doprzodu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459)))
                .addGap(20, 20, 20))
        );
        Wyszukiwanie1_4Layout.setVerticalGroup(
            Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ile_wynikow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wroc2)
                .addGap(49, 49, 49)
                .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                        .addComponent(P1Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(P1T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                        .addComponent(P2Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(P2T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                                .addComponent(P4Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P4T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Wyszukiwanie1_4Layout.createSequentialGroup()
                                .addComponent(P3Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P3T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(Wyszukiwanie1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doprzodu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofnij1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        Wyszukiwanie4_8.setBackground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie4_8.setForeground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie4_8.setAlignmentX(0.0F);
        Wyszukiwanie4_8.setAlignmentY(0.0F);
        Wyszukiwanie4_8.setPreferredSize(new java.awt.Dimension(1060, 600));

        ile_wynikow1.setText("ZNALEZIONO WYNIKÓW");

        P5Z.setText("P5Z");
        P5Z.setName("P1Z"); // NOI18N
        P5Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P5TMouseClicked(evt);
            }
        });

        P5T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P5T.setText("P5T");
        P5T.setName("P1T"); // NOI18N
        P5T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P5TMouseClicked(evt);
            }
        });

        P6Z.setText("P6Z");
        P6Z.setName("P1Z"); // NOI18N
        P6Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P6TMouseClicked(evt);
            }
        });

        P6T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P6T.setText("P6T");
        P6T.setName("P1T"); // NOI18N
        P6T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P6TMouseClicked(evt);
            }
        });

        P8Z.setText("P8Z");
        P8Z.setName("P1Z"); // NOI18N
        P8Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P8TMouseClicked(evt);
            }
        });

        P7Z.setText("P7Z");
        P7Z.setName("P1Z"); // NOI18N
        P7Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P7TMouseClicked(evt);
            }
        });

        P8T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P8T.setText("P8T");
        P8T.setName("P1T"); // NOI18N
        P8T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P8TMouseClicked(evt);
            }
        });

        P7T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P7T.setText("P7T");
        P7T.setName("P1T"); // NOI18N
        P7T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P7TMouseClicked(evt);
            }
        });

        doprzodu2.setText("→");
        doprzodu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doprzodu2ActionPerformed(evt);
            }
        });

        cofnij2.setText("←");
        cofnij2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofnij2ActionPerformed(evt);
            }
        });

        wroc3.setText("Wróć do menu głównego");
        wroc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Wyszukiwanie4_8Layout = new javax.swing.GroupLayout(Wyszukiwanie4_8);
        Wyszukiwanie4_8.setLayout(Wyszukiwanie4_8Layout);
        Wyszukiwanie4_8Layout.setHorizontalGroup(
            Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wyszukiwanie4_8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cofnij2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doprzodu2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(ile_wynikow1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wroc3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Wyszukiwanie4_8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P5Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P5T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P6Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P6T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P7Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P7T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P8Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P8T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        Wyszukiwanie4_8Layout.setVerticalGroup(
            Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ile_wynikow1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wroc3))
                .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                                .addComponent(P5Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P5T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                                .addComponent(P6Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P6T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                                .addComponent(P8Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P8T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Wyszukiwanie4_8Layout.createSequentialGroup()
                                .addComponent(P7Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P7T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(Wyszukiwanie4_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doprzodu2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofnij2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        Wyszukiwanie8_12.setBackground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie8_12.setForeground(new java.awt.Color(255, 245, 186));
        Wyszukiwanie8_12.setAlignmentX(0.0F);
        Wyszukiwanie8_12.setAlignmentY(0.0F);
        Wyszukiwanie8_12.setPreferredSize(new java.awt.Dimension(1060, 600));

        ile_wynikow2.setText("ZNALEZIONO WYNIKÓW");

        P9Z.setText("P9Z");
        P9Z.setName("P1Z"); // NOI18N
        P9Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P9TMouseClicked(evt);
            }
        });

        P9T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P9T.setText("P9T");
        P9T.setName("P1T"); // NOI18N
        P9T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P9TMouseClicked(evt);
            }
        });

        P10Z.setText("P10Z");
        P10Z.setName("P1Z"); // NOI18N
        P10Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P10TMouseClicked(evt);
            }
        });

        P10T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P10T.setText("P10T");
        P10T.setName("P1T"); // NOI18N
        P10T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P10TMouseClicked(evt);
            }
        });

        P12Z.setText("P12Z");
        P12Z.setName("P1Z"); // NOI18N

        P11Z.setText("P11Z");
        P11Z.setName("P1Z"); // NOI18N
        P11Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P11TMouseClicked(evt);
            }
        });

        P12T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P12T.setText("P12T");
        P12T.setName("P1T"); // NOI18N
        P12T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P12TMouseClicked(evt);
            }
        });

        P11T.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        P11T.setText("P11T");
        P11T.setName("P1T"); // NOI18N
        P11T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P11TMouseClicked(evt);
            }
        });

        doprzodu3.setText("→");
        doprzodu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doprzodu3ActionPerformed(evt);
            }
        });

        cofnij3.setText("←");
        cofnij3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofnij3ActionPerformed(evt);
            }
        });

        wroc4.setText("Wróć do menu głównego");
        wroc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Wyszukiwanie8_12Layout = new javax.swing.GroupLayout(Wyszukiwanie8_12);
        Wyszukiwanie8_12.setLayout(Wyszukiwanie8_12Layout);
        Wyszukiwanie8_12Layout.setHorizontalGroup(
            Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wyszukiwanie8_12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cofnij3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doprzodu3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P9Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P9T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P10Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P10T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P11Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                                .addGap(1015, 1015, 1015)
                                .addComponent(P11T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P12Z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P12T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wroc4))
                    .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ile_wynikow2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Wyszukiwanie8_12Layout.setVerticalGroup(
            Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ile_wynikow2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wroc4)
                        .addGap(46, 46, 46)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                                .addComponent(P9Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P9T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                                .addComponent(P10Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P10T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                                .addComponent(P12Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P12T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Wyszukiwanie8_12Layout.createSequentialGroup()
                                .addComponent(P11Z, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P11T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(Wyszukiwanie8_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doprzodu3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofnij3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        categoriesPage.setBackground(new java.awt.Color(255, 245, 186));
        categoriesPage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        categoriesPage.setForeground(new java.awt.Color(255, 245, 186));
        categoriesPage.setAlignmentX(0.0F);
        categoriesPage.setAlignmentY(0.0F);
        categoriesPage.setPreferredSize(new java.awt.Dimension(1011, 550));

        tytul1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tytul1.setText("KSIĄŻKA KUCHARSKA");

        lista_przepisow.setBackground(new java.awt.Color(102, 102, 255));
        lista_przepisow.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lista_przepisow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_przepisowActionPerformed(evt);
            }
        });
        lista_przepisow.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lista_przepisowPropertyChange(evt);
            }
        });

        pom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pom.setText("Wybierz kategorie aby zobaczyć znajdujące się w niej przepisy");
        pom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout categoriesPageLayout = new javax.swing.GroupLayout(categoriesPage);
        categoriesPage.setLayout(categoriesPageLayout);
        categoriesPageLayout.setHorizontalGroup(
            categoriesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriesPageLayout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addGroup(categoriesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoriesPageLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(pom1))
                    .addGroup(categoriesPageLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(lista_przepisow, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(categoriesPageLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(pom))
                    .addGroup(categoriesPageLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(tytul1)))
                .addGap(253, 253, 253))
        );
        categoriesPageLayout.setVerticalGroup(
            categoriesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tytul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista_przepisow, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        recipePage.setBackground(new java.awt.Color(255, 245, 186));
        recipePage.setForeground(new java.awt.Color(255, 245, 186));
        recipePage.setAlignmentX(0.0F);
        recipePage.setAlignmentY(0.0F);
        recipePage.setPreferredSize(new java.awt.Dimension(1060, 600));

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane3.setAutoscrolls(true);

        wyswietl_tekst.setBackground(new java.awt.Color(102, 102, 255));
        wyswietl_tekst.setText("tu wyświetl tekst");
        wyswietl_tekst.setToolTipText("");
        jScrollPane3.setViewportView(wyswietl_tekst);

        zapisz.setText("ZAPISZ PRZEPIS");
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });

        drukuj.setText("DRUKUJ PRZEPIS");
        drukuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drukujActionPerformed(evt);
            }
        });

        wroc.setText("WRÓĆ DO MENU GŁÓWNEGO");
        wroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocActionPerformed(evt);
            }
        });

        tytul_przepisu.setText("tytul przepisu");

        javax.swing.GroupLayout recipePageLayout = new javax.swing.GroupLayout(recipePage);
        recipePage.setLayout(recipePageLayout);
        recipePageLayout.setHorizontalGroup(
            recipePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePageLayout.createSequentialGroup()
                .addGroup(recipePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipePageLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tytul_przepisu))
                    .addGroup(recipePageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recipePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(wroc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drukuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zapisz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wyswietl_zdjecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        recipePageLayout.setVerticalGroup(
            recipePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePageLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(tytul_przepisu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recipePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipePageLayout.createSequentialGroup()
                        .addComponent(wyswietl_zdjecie, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zapisz)
                        .addGap(18, 18, 18)
                        .addComponent(drukuj)
                        .addGap(18, 18, 18)
                        .addComponent(wroc))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        aboutPage.setBackground(new java.awt.Color(255, 245, 186));
        aboutPage.setForeground(new java.awt.Color(255, 245, 186));
        aboutPage.setAlignmentX(0.0F);
        aboutPage.setAlignmentY(0.0F);
        aboutPage.setPreferredSize(new java.awt.Dimension(1060, 600));

        wroc5.setText("Wróć do menu głównego");
        wroc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wroc2actionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("<html>Ta aplikacja powstała jako projekt zaliczeniowy z przedmiotu Programowanie w Javie. <br>Jest ona wirtualną książką kucharską z funkcją wyszukiwania przepisów, <br> jak również zapisywania oraz drukowania ich zawartości. <br>Autorzy:<br>* Julia Olszewska <br> * Andrzej Kozińśki <br> * Mikołaj Sobiegraj</html>");

        javax.swing.GroupLayout aboutPageLayout = new javax.swing.GroupLayout(aboutPage);
        aboutPage.setLayout(aboutPageLayout);
        aboutPageLayout.setHorizontalGroup(
            aboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wroc5)
                .addGap(51, 51, 51))
            .addGroup(aboutPageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        aboutPageLayout.setVerticalGroup(
            aboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPageLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(wroc5)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aboutPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Wyszukiwanie8_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 25, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(Wyszukiwanie4_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(recipePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(Wyszukiwanie1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(categoriesPage, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(566, 566, 566))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Wyszukiwanie8_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(aboutPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Wyszukiwanie4_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(recipePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Wyszukiwanie1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(categoriesPage, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public List<Recipe> przeszukajkategorie() {
        String categoryText = searchInput.getText();
        List<Recipe> znalezione = new ArrayList();
        for (Recipe recipe : repository.getAllRecipies()) {
            if (recipe.getCategories().contains(categoryText)) {
                znalezione.add(recipe);
            }
        }
        return znalezione;
    }

    //CONTROLLER     
    public class PrzepisController {

        public Recipe model;
        public NewJFrame.PrzepisView view;

        public PrzepisController(Recipe model, NewJFrame.PrzepisView view) {
            this.model = model;
            this.view = view;
        }

        void wyswietl_caly_przepis_controller(JLabel miejscenazdjecie, JLabel miejscenatekst, String tekstprzepisu) {
            view.wyswietl_caly_przepis(model, miejscenazdjecie, miejscenatekst, model.getTekstPrzepisuSformatowany());
        }

        void wyswietl_zdjecie_i_tytul_controller(JLabel miejscenazdjecie, JLabel miejscenatekst) {
            view.wyswietl_zdjecie_i_tytul(model, miejscenazdjecie, miejscenatekst);
        }
    }

    //VIEW        
    public class PrzepisView {

        public void wyswietl_caly_przepis(Recipe przepis, JLabel miejscenazdjecie, JLabel miejscenatekst, String tekstprzepisu) {
            ImageIcon iconLogo = new ImageIcon(przepis.getImagePath());
            miejscenazdjecie.setIcon(iconLogo);
            miejscenatekst.setText(tekstprzepisu);
        }

        public void wyswietl_zdjecie_i_tytul(Recipe przepis, JLabel miejscenazdjecie, JLabel miejscenatekst) {
            ImageIcon iconLogo = new ImageIcon(przepis.getImagePath());
            miejscenazdjecie.setText("");
            miejscenazdjecie.setIcon(iconLogo);
            miejscenatekst.setText(przepis.getTitle());
        }
    }

    void wyswietlprzepis(JLabel label) {
        if (Wyszukiwanie1_4.isVisible()) {
            Wyszukiwanie1_4.setVisible(false);
        }
        if (Wyszukiwanie4_8.isVisible()) {
            Wyszukiwanie4_8.setVisible(false);
        }
        if (Wyszukiwanie8_12.isVisible()) {
            Wyszukiwanie8_12.setVisible(false);
        }

        recipePage.setVisible(true); // TODO add your handling code here:

        String tytul = label.getText();
        Recipe wybranyprzepis = null;
        for (Recipe przepisy1 : repository.getAllRecipies()) {
            if (przepisy1.getTitle() == tytul) {
                wybranyprzepis = przepisy1;
            }
        }
        PrzepisView view = new PrzepisView();
        PrzepisController controller = new PrzepisController(wybranyprzepis, view);
        controller.wyswietl_caly_przepis_controller(wyswietl_zdjecie, wyswietl_tekst, wybranyprzepis.getTekstPrzepisuSformatowany());
        tytul_przepisu.setText(wybranyprzepis.getTitle());

    }

    public JLabel znajdz_label(String nazwa) {

        for (int j = 0; j <= Wyszukiwanie1_4.getComponents().length; j++) {
            if (Wyszukiwanie1_4.getComponent(j) instanceof JLabel) {
                JLabel label = (JLabel) Wyszukiwanie1_4.getComponent(j);
                if (label.getText() == null ? nazwa == null : label.getText().equals(nazwa)) {
                    return label;
                }

            }
        }
        for (int j = 0; j <= Wyszukiwanie4_8.getComponents().length; j++) {
            if (Wyszukiwanie1_4.getComponent(j) instanceof JLabel) {
                JLabel label = (JLabel) Wyszukiwanie4_8.getComponent(j);
                if (label.getText() == null ? nazwa == null : label.getText().equals(nazwa)) {
                    return label;
                }

            }
        }
        for (int j = 0; j <= Wyszukiwanie8_12.getComponents().length; j++) {
            if (Wyszukiwanie1_4.getComponent(j) instanceof JLabel) {
                JLabel label = (JLabel) Wyszukiwanie8_12.getComponent(j);
                if (label.getText() == null ? nazwa == null : label.getText().equals(nazwa)) {
                    return label;
                }

            }
        }
        return null;
    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mainPage.setVisible(true);
        Wyszukiwanie1_4.setVisible(false);
        Wyszukiwanie4_8.setVisible(false);
        Wyszukiwanie8_12.setVisible(false);
        recipePage.setVisible(false);
        aboutPage.setVisible(false);
        categoriesPage.setVisible(false);
        categoriesButton.setVisible(false);
        aboutButton.setVisible(false);

        initializeRepository();
        
        String grafika = System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\cookbook4.png";
        ImageIcon imageIcon = new ImageIcon(grafika);
        image.setText("");
        image.setIcon(imageIcon);
    }//GEN-LAST:event_formWindowOpened

    private void initializeRepository() {
        repository = new Repository();
        Recipe recipe = new Recipe();
        recipe.addCategory("obiad"); 
        recipe.setTitle("zupa");
        recipe.setDescription("cosik");
        recipe.setImagePath(System.getProperty("user.dir") + "\\src\\main\\java\\Zdjecia\\szarlotka.jpg");

        repository.addRecipe(recipe);
    }


    private void doprzodu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doprzodu1ActionPerformed
        Wyszukiwanie1_4.setVisible(false);
        Wyszukiwanie4_8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_doprzodu1ActionPerformed

    private void doprzodu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doprzodu2ActionPerformed
        Wyszukiwanie4_8.setVisible(false);
        Wyszukiwanie8_12.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_doprzodu2ActionPerformed

    private void cofnij2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofnij2ActionPerformed
        Wyszukiwanie4_8.setVisible(false);
        Wyszukiwanie1_4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_cofnij2ActionPerformed

    private void cofnij3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofnij3ActionPerformed
        Wyszukiwanie8_12.setVisible(false);
        Wyszukiwanie4_8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_cofnij3ActionPerformed

    private void doprzodu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doprzodu3ActionPerformed
        Wyszukiwanie8_12.setVisible(false);
        Wyszukiwanie1_4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_doprzodu3ActionPerformed

    private void cofnij1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofnij1ActionPerformed
        Wyszukiwanie1_4.setVisible(false);
        Wyszukiwanie8_12.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_cofnij1ActionPerformed


    private void P1TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1TMouseClicked
        JLabel label = P1T;
        wyswietlprzepis(label);
    }//GEN-LAST:event_P1TMouseClicked

    private void P2TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2TMouseClicked
        JLabel label = P2T;
        wyswietlprzepis(label);    // TODO add your handling code here:
    }//GEN-LAST:event_P2TMouseClicked

    private void P3TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3TMouseClicked
        JLabel label = P3T;
        wyswietlprzepis(label);       // TODO add your handling code here:
    }//GEN-LAST:event_P3TMouseClicked

    private void P4TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4TMouseClicked
        JLabel label = P4T;
        wyswietlprzepis(label);    // TODO add your handling code here:
    }//GEN-LAST:event_P4TMouseClicked

    private void P5TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P5TMouseClicked
        JLabel label = P5T;
        wyswietlprzepis(label);     // TODO add your handling code here:
    }//GEN-LAST:event_P5TMouseClicked

    private void P6TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P6TMouseClicked
        JLabel label = P6T;
        wyswietlprzepis(label);     // TODO add your handling code here:
    }//GEN-LAST:event_P6TMouseClicked

    private void P7TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P7TMouseClicked
        JLabel label = P7T;
        wyswietlprzepis(label);       // TODO add your handling code here:
    }//GEN-LAST:event_P7TMouseClicked

    private void P8TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P8TMouseClicked
        JLabel label = P8T;
        wyswietlprzepis(label);         // TODO add your handling code here:
    }//GEN-LAST:event_P8TMouseClicked

    private void P9TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P9TMouseClicked
        JLabel label = P9T;
        wyswietlprzepis(label);     // TODO add your handling code here:
    }//GEN-LAST:event_P9TMouseClicked

    private void P10TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P10TMouseClicked
        JLabel label = P10T;
        wyswietlprzepis(label);       // TODO add your handling code here:
    }//GEN-LAST:event_P10TMouseClicked

    private void P11TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P11TMouseClicked
        JLabel label = P11T;
        wyswietlprzepis(label);       // TODO add your handling code here:
    }//GEN-LAST:event_P11TMouseClicked

    private void P12TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P12TMouseClicked
        JLabel label = P12T;
        wyswietlprzepis(label);
        // TODO add your handling code here:
    }//GEN-LAST:event_P12TMouseClicked

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed

        try {
            FileWriter myWriter = new FileWriter(tytul_przepisu.getText());
            myWriter.write(wyswietl_tekst.getText());
            myWriter.close();
        } catch (IOException e) {
            System.out.println("Błąd zapisu do pliku");
            e.printStackTrace();
        }
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String tuzapisz = fileChooser.getCurrentDirectory().getAbsolutePath() + "/" + fileChooser.getSelectedFile().getName() + ".txt";

            try {
                Writer output = null;
                File file = new File(tuzapisz);
                output = new BufferedWriter(new FileWriter(file));
                output.write(wyswietl_tekst.getText());
                output.close();

            } catch (Exception e) {
                System.out.println("Błąd w czasie tworzenia pliku");
            }

        }


    }//GEN-LAST:event_zapiszActionPerformed


    private void drukujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drukujActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        if (pj.printDialog()) {
            try {
                pj.print();
            } catch (PrinterException exc) {
                System.out.println(exc);
            }
        }
    }//GEN-LAST:event_drukujActionPerformed

    private void wrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocActionPerformed
        recipePage.setVisible(false);
        mainPage.setVisible(true);
        dispose();//Reset aplikacji
        NewJFrame frame = new NewJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_wrocActionPerformed

    private void lista_przepisowPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lista_przepisowPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_przepisowPropertyChange

    private void pomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pomMouseClicked

    private void lista_przepisowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_przepisowActionPerformed
        String wybrany = lista_przepisow.getSelectedItem();
        categoriesPage.setVisible(false);
        searchInput.setText(wybrany);
        byCategoriesSearch.setSelected(true);
        searchButtonActionPerformed(evt);
    }//GEN-LAST:event_lista_przepisowActionPerformed

    private void wroc2actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wroc2actionPerformed
        Wyszukiwanie1_4.setVisible(false);
        mainPage.setVisible(true);
        dispose();//Reset aplikacji
        NewJFrame frame = new NewJFrame();
        frame.setVisible(true);
 
    }//GEN-LAST:event_wroc2actionPerformed

    private void categoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesButtonActionPerformed
        mainPage.setVisible(false);
        categoriesPage.setVisible(true);

        for (String kategoria : repository.getAllCategories()) {
            lista_przepisow.add(kategoria);
        }
    }//GEN-LAST:event_categoriesButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        mainPage.setVisible(false);
        aboutPage.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        if (categoriesButton.isVisible() == false) {
            categoriesButton.setVisible(true);
            aboutButton.setVisible(true);
        } else {
            categoriesButton.setVisible(false);
            aboutButton.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

//POPRAWIĆ TO, ŻEBY BYŁO ZGODNE Z MVC
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        List<Recipe> wyniki = new ArrayList();
        Wyszukiwanie1_4.setVisible(false);

        if (searchInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(wybierz_kategorie, "Wpisz tekst do wyszukania");
        } else if (!byDescriptionSearch.isSelected() && !byCategoriesSearch.isSelected()) {
            JOptionPane.showMessageDialog(wybierz_kategorie, "Wybierz jedną z kategorii wyszukiwania");
        } else {
            if (byDescriptionSearch.isSelected()) {
                wyniki = repository.getRecipesWithText(searchInput.getText());
            }

            if (byCategoriesSearch.isSelected()) {
                wyniki = przeszukajkategorie();
            }

            mainPage.setVisible(false);
            Wyszukiwanie1_4.setVisible(true);

            updateSearchResultCount(wyniki.size());

            wroc2.setVisible(true);

            if (wyniki.size() > 4) {
                doprzodu1.setEnabled(true);
                doprzodu1.setVisible(true);
                cofnij1.setVisible(true);

            }

            for (int i = 1; i <= wyniki.size(); i++) {
                String nazwa_tekst = "P" + i + "T";
                String nazwa_zdjecie = "P" + i + "Z";
                JLabel label_tekst = znajdz_label(nazwa_tekst);
                label_tekst.setVisible(true);
                JLabel label_zdjecie = znajdz_label(nazwa_zdjecie);
                label_zdjecie.setVisible(true);
                int nowei = i - 1;

                PrzepisView view = new PrzepisView();
                PrzepisController controller = new PrzepisController(wyniki.get(nowei), view);
                controller.wyswietl_zdjecie_i_tytul_controller(label_zdjecie, label_tekst);

            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateSearchResultCount(int count) {
        String a = null; 
        if (count == 1) {
            a = "Znaleziono " + count + " wynik";
        }
        if (2 <= count && count <= 4) {
            a = "Znaleziono " + count + " wyniki";
        }
        if (count >= 5) {
            a = "Znaleziono " + count + " wyników";
        }
        ile_wynikow.setText(a);
        ile_wynikow.setVisible(true);
    }
    private void byCategoriesSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byCategoriesSearchActionPerformed
        if (!byDescriptionSearch.isSelected()) {
            byCategoriesSearch.setSelected(true);
            byDescriptionSearch.setSelected(false);
        } else {
            byCategoriesSearch.setSelected(true);
            byDescriptionSearch.setSelected(false);
        }
        // TODO add your handl  // TODO add your handling code here:
    }//GEN-LAST:event_byCategoriesSearchActionPerformed

    private void byDescriptionSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byDescriptionSearchActionPerformed
        if (!byCategoriesSearch.isSelected()) {
            byDescriptionSearch.setSelected(true);
            byCategoriesSearch.setSelected(false);
        } else {
            byDescriptionSearch.setSelected(true);
            byCategoriesSearch.setSelected(false);

        }// TODO add your handling code here:
    }//GEN-LAST:event_byDescriptionSearchActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NewJFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P10T;
    private javax.swing.JLabel P10Z;
    private javax.swing.JLabel P11T;
    private javax.swing.JLabel P11Z;
    private javax.swing.JLabel P12T;
    private javax.swing.JLabel P12Z;
    private javax.swing.JLabel P1T;
    private javax.swing.JLabel P1Z;
    private javax.swing.JLabel P2T;
    private javax.swing.JLabel P2Z;
    private javax.swing.JLabel P3T;
    private javax.swing.JLabel P3Z;
    private javax.swing.JLabel P4T;
    private javax.swing.JLabel P4Z;
    private javax.swing.JLabel P5T;
    private javax.swing.JLabel P5Z;
    private javax.swing.JLabel P6T;
    private javax.swing.JLabel P6Z;
    private javax.swing.JLabel P7T;
    private javax.swing.JLabel P7Z;
    private javax.swing.JLabel P8T;
    private javax.swing.JLabel P8Z;
    private javax.swing.JLabel P9T;
    private javax.swing.JLabel P9Z;
    private javax.swing.JPanel Wyszukiwanie1_4;
    private javax.swing.JPanel Wyszukiwanie4_8;
    private javax.swing.JPanel Wyszukiwanie8_12;
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel aboutPage;
    private javax.swing.JLabel appTitle;
    private javax.swing.JRadioButton byCategoriesSearch;
    private javax.swing.JRadioButton byDescriptionSearch;
    private javax.swing.JButton categoriesButton;
    private javax.swing.JPanel categoriesPage;
    private javax.swing.JButton cofnij1;
    private javax.swing.JButton cofnij2;
    private javax.swing.JButton cofnij3;
    private javax.swing.JButton doprzodu1;
    private javax.swing.JButton doprzodu2;
    private javax.swing.JButton doprzodu3;
    private javax.swing.JButton drukuj;
    private java.awt.Label ile_wynikow;
    private java.awt.Label ile_wynikow1;
    private java.awt.Label ile_wynikow2;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.List lista_przepisow;
    private javax.swing.JPanel mainPage;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel pom;
    private javax.swing.JLabel pom1;
    private javax.swing.JPanel recipePage;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel tytul1;
    private javax.swing.JLabel tytul_przepisu;
    private javax.swing.JButton wroc;
    private javax.swing.JButton wroc2;
    private javax.swing.JButton wroc3;
    private javax.swing.JButton wroc4;
    private javax.swing.JButton wroc5;
    private javax.swing.JDialog wybierz_kategorie;
    private javax.swing.JLabel wyswietl_tekst;
    private javax.swing.JLabel wyswietl_zdjecie;
    private javax.swing.JButton zapisz;
    // End of variables declaration//GEN-END:variables
}
